workflow:
     rules: 
       - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
         when: never
       - when: always

run_unit_test:
      image: node:17-alpine3.14
      tags: 
        - ec2
        - docker
        - remote
      before_scipt: 
        - cd app
        - npm install
      script:
        - npm test